# These are supported funding model platforms

github: [toddwildey]
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/sublime-text-plugin-pip
