name: Release to PyPI

permissions:
  contents: write

on:
  push:
    branches: [ main ]

env:
  FORCE_COLOR: '1'

jobs:
  build:
    name: Build dist files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Build dist
      run: python -m build

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          dist
        if-no-files-found: error

  publish-to-pypi:
    name: Release to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
      url: https://pypi.org/project/sublime-text-plugin-pip/
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Release to Test PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi-release
      url: https://test.pypi.org/project/sublime-text-plugin-pip/
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # skip-existing: true
        repository-url: https://test.pypi.org/legacy/
